### ISSUE TITLE
[Feature] 可以增加重力感应版本的嘛？Sensors

### ISSUE THREAD

**Issue by MR-MaoJiu** [fluttercandies/flutter_tilt#1]
可不可以增加一个重力感应的模块可以选择手势/重力感应/两者都是

**Comment by AmosHuKe** [comment]
@MR-MaoJiu 
Hi~ 感谢你的建议，目前已经有了一个相对完整的预发行版本：[flutter_tilt: ^2.0.0-dev.3](https://pub.dev/packages/flutter_tilt/versions/2.0.0-dev.3)，
有什么问题随时提出，感谢使用~
（测试完整后将会发布正式版）
2.0.0-dev.3 预发行版本的文档请从下方点击查看，目前正式版还未更新文档。

## 迁移指南 Migration guide
如果你需要从1.x.x 版本升级，请先阅读：[迁移指南](https://github.com/AmosHuKe/flutter_tilt/blob/dev/guides/migration_guide.md#200)。
If you are upgrading from version 1.x.x, please read: [migration guide](https://github.com/AmosHuKe/flutter_tilt/blob/dev/guides/migration_guide.md#200).

## 文档 Document
v2.0.0-dev.3 [中文文档](https://github.com/AmosHuKe/flutter_tilt/blob/v2.0.0-dev.3/README-ZH.md)
v2.0.0-dev.3 [English document](https://github.com/AmosHuKe/flutter_tilt/blob/v2.0.0-dev.3/README.md)
