### ISSUE TITLE
After use, the mobile phone fever is serious, please check what is the reason

### ISSUE THREAD

**Issue by yoyo89757001** [fluttercandies/flutter_tilt#4]
After use, the mobile phone fever is serious, please check what is the reason

**Comment by yoyo89757001** [comment]
iOS is more obvious

**Comment by AmosHuKe** [comment]
@yoyo89757001 Thank you for your feedback! 😄

`flutter_tilt v2.1.2` improved this issue.

Cause of mobile phone overheating: `High Energy Impact`.

## Before

> Run mode: profile

- Default configuration:
  <img width="640px" alt="Before" src="https://github.com/fluttercandies/flutter_tilt/assets/32262985/06063e1c-0b9f-4e24-b039-378def5f0ff6"/>

- Disable sensors: `Tilt(tiltConfig: const TiltConfig(enableGestureSensors: false))`
  <img width="640px" alt="Before" src="https://github.com/fluttercandies/flutter_tilt/assets/32262985/c9baf5d9-0344-43c4-bcda-b6dcab860af7"/>

## After (flutter_tilt v2.1.2)

> Run mode: profile

- Default configuration:
  <img width="640px" alt="After" src="https://github.com/fluttercandies/flutter_tilt/assets/32262985/f58c646a-9516-493a-a756-c9aacc0d3c6f"/>

- Disable sensors: `Tilt(tiltConfig: const TiltConfig(enableGestureSensors: false))`
  <img width="640px" alt="After" src="https://github.com/fluttercandies/flutter_tilt/assets/32262985/c3f1d37e-348d-45bf-865a-71b0ce6ec396"/>

**Comment by yoyo89757001** [comment]
Thanks for the improvement, I need to test the new version

**Comment by AmosHuKe** [comment]
@yoyo89757001 I have tested Android and iOS platforms.
If the problem persists, I will reopen the issue. 😄
