### ISSUE TITLE
This prompt appears on iOS

### ISSUE THREAD

**Issue by yoyo89757001** [fluttercandies/flutter_tilt#6]
The 'dev.fluttercommunity.plus/sensors/gyroscope' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

**Comment by AmosHuKe** [comment]
@yoyo89757001 
Thanks for the feedback! 😄

The source of the error message is the `sensors_plus` package.

You can follow the same issue: https://github.com/fluttercommunity/plus_plugins/issues/2342#issuecomment-1817963563

I'm using Flutter 3.16.0 which reproduce this issue,
but the sensors are still working fine.

If your software works fine in the release version, you can ignore this prompt for now.
I'll keep track of the sensors_plus package and keep the sensors_plus version up to date.

**Comment by AmosHuKe** [comment]
Fixed, please upgrade to flutter_tilt v2.2.0
Changelog: [v2.2.0](https://github.com/fluttercandies/flutter_tilt/blob/main/CHANGELOG.md#220)
