### ISSUE TITLE
[Feature] Disable Features on Low Power Mode

### ISSUE THREAD

**Issue by SethuSenthil** [fluttercandies/flutter_tilt#7]
It would be great if there was a global option, per widget option to turn off the tilt, or sensor-based tilt on low power mode to preserve the battery, thank!

**Comment by AmosHuKe** [comment]
@SethuSenthil hi~
If you want to turn off the sensor in low power mode,
You can configure `TiltConfig -> enableGestureSensors` to turn off the sensors completely.
> Currently, You will need to determine the low power mode before you can configure it.
> Other gestures (touch, hover) still work.

```dart
Tilt(
  TiltConfig: TiltConfig(
    enableGestureSensors: false,
  ),
  child: ......
)
```
